service: aws-node
frameworkVersion: '3'

provider: # Proveedor del servicio/ donde lo vamos a almacenar
  name: aws
  runtime: nodejs18.x

plugins: # los plugins que utilicemos se deben añadir en esta sección
  - serverless-offline

functions: # las funciones de acceso a nuestra app. Esto funciona como una especie de Gateway
  api: # Nombre de la función del api gateway
    handler: index.handler # Encargado de manejar la petición
    events: # Eventos esperados
      - httpApi: # Evento tipo http (Accediendo a la función mediante una llamada http)
          path: / # Path o dirección url de acceso a la función
          method: get # Tipo de petición a realizar
  getItems:
    handler: ./services/list.getItems
    events: # Que eventos se pueden realizar
      - httpApi: # Eventos tipos http
          path: /items/ # Path de acceso al evento
          method: get # Metodo que acepta el evento http
  createItem:
    handler: ./services/create.createItem
    events:
      - httpApi:
          path: /item/
          method: post
  updateItem:
    handler: ./services/update.updateItem
    events: # Que eventos se pueden realizar
      - httpApi: # Eventos tipos http
          path: /items/{id} # Path de acceso al evento. El {id} es la variable que se obtiene mediante la url (PathParametter)
          method: put # Metodo que acepta el evento http
  deleteItem:
    handler: ./services/delete.deleteItem
    events:
      - httpApi:
          path: /item/{id}
          method: delete
